before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: gh-grep-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-grep.version={{.Version}} -X github.com/k1LoW/gh-grep.commit={{.FullCommit}} -X github.com/k1LoW/gh-grep.date={{.Date}} -X github.com/k1LoW/gh-grep/version.Version={{.Version}}
-
  id: gh-grep-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-grep.version={{.Version}} -X github.com/k1LoW/gh-grep.commit={{.FullCommit}} -X github.com/k1LoW/gh-grep.date={{.Date}} -X github.com/k1LoW/gh-grep/version.Version={{.Version}}
-
  id: gh-grep-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-grep.version={{.Version}} -X github.com/k1LoW/gh-grep.commit={{.FullCommit}} -X github.com/k1LoW/gh-grep.date={{.Date}} -X github.com/k1LoW/gh-grep/version.Version={{.Version}}
archives:
-
  id: gh-grep-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - CREDITS
    - README.md
    - CHANGELOG.md
  rlcp: true
-
  id: gh-grep-binary
  name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: binary
  rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
nfpms:
  - id: gh-grep-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - gh-grep-linux
    homepage: https://github.com/k1LoW/gh-grep
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: Print lines matching a pattern in repositories using GitHub API
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
