#!/usr/bin/env bash
set -e

extensionPath="$(dirname "$0")"

cd "${extensionPath}" > /dev/null
tag="$(git tag | grep ^v | sort --version-sort | tail -1)"
cd - > /dev/null

arch="$(uname -m)"

exe=""

if uname -a | grep Msys > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-grep_${tag}_windows_amd64.exe"
  fi
elif uname -a | grep Darwin > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-grep_${tag}_darwin_amd64"
  elif [ $arch = "arm64" ]; then
    exe="gh-grep_${tag}_darwin_arm64"
  fi
elif uname -a | grep Linux > /dev/null; then
  if [ $arch = "x86_64" ]; then
    exe="gh-grep_${tag}_linux_amd64"
  fi
fi

rm -f "${extensionPath}/bin/*"
mkdir -p "${extensionPath}/bin"

if [ "${exe}" == "" ]; then
  if [ "$(which go)" = "" ]; then
    echo "go must be installed to use this gh extension on this platform"
    exit 1
  fi

  exe="cmd.out"

  cd "${extensionPath}" > /dev/null
  go build -o "${extensionPath}/bin/${exe}"
  cd - > /dev/null
else
  if [[ ! -x "${extensionPath}/bin/${exe}" ]]; then
    if [ "$(which curl)" = "" ]; then
      echo "curl must be installed to use this gh extension on this platform"
      exit 1
    fi
    curl -sL -o "${extensionPath}/bin/${exe}" https://github.com/k1LoW/gh-grep/releases/download/${tag}/${exe}
  fi
fi
chmod +x "${extensionPath}/bin/${exe}"

exec "${extensionPath}/bin/${exe}" "$@"
